### ISSUE TITLE
Webhost is not CORS enabled

### ISSUE THREAD

**Issue by xqiu** [gustavo-armenta/CookieAuthenticationSample#1]
Webhost is not CORS enabled, so using chrome with JavaScriptClient will not work.   The problem is webhost is a MVC5 RC bit, our current implementation of CORS attributre support is only for webAPI controller.  And it actually make sense, no one will want their MVC5 controllers to be CORS enabled.

So there are a few options:
1. Make it clear in readme that this will only work in IE
2. Create a webAPI and cookie based webHost with CORS support (note, webapi v2 default is using bearer instead of cookie)

**Comment by gustavo-armenta** [comment]
fixed, now it works for all transports on CORS

45c4104afbe90b83d4cadf5f7d41264b0376af12

**Comment by xqiu** [comment]
If you try in chrome: http://localhost:31111/AuthorizeEchoHub.html against webhost, it will still not work, it might due to CORS issue that we cannot get login MVC page.  MVC controller does not support CORS seems like.

**Comment by gustavo-armenta** [comment]
Please try again, this is the scenario:
1. Start WebHost
2. Start JavaScript client
3. Navigate to http://localhost:31111/index.html, input credentials
4. Navigate to http://localhost:31111/AuthorizeEchoConnection.html

**Comment by xqiu** [comment]
Yeah, this works.  Sorry I made a mistake when verifying chrome...
